name: Deploy Dashboard
on:
  push:
    branches:
      - main
      - development
      - ks5-timeseries-development
      - eesp/maintenance-2025-feb
  pull_request:
    branches:
      - main
  
jobs:
  deploy:
    uses: dfe-analytical-services/dfeshiny/.github/workflows/dashboard_deploy_template.yaml@main
    with:
      parameter_file: deploy-parameters.yaml
    secrets:
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      
